### ISSUE TITLE
Changes to api?

### ISSUE THREAD

**Issue by onlymejosh** [vzaar/vzaar-api-ruby#13]
It looks like you've released a new version which solves the signature issue? 

I'm unsure how the signature part is supposed to work if you are uploading directly to S3 you won't have a path for the video.

**Comment by edjames** [comment]
Hi

The new version now requires either a `path` or `url` argument. The reason for this is the type of signature we generate.

If you are uploading from your filesystem then use the absolute path to your file as the value for the `path`. If you are handling this yourself through your own front-end, we have a demo application which illustrates this behaviour (sorry, it's in php): https://github.com/vzaar/chunked-browser-upload-reference-implementation.

If you specify a `path` when requesting a signature, then we also check for the presence of optional `filename` and `filesize` arguments (handled internally in the gem). If these exist we use these to determine if we should initiate a MultipartUpload on S3. The new version of the gem now supports multipart uploads. 

If you specify a `url` when requesting a signature, we bypass the checks described above and simply return a signature.

I've updated the README too.

Let me know if you need any more help.

**Comment by onlymejosh** [comment]
Hi,

I'm still a little confused by the `url` part. I won't know the url of the video until after it has been uploaded? The videos will be hosted on your S3 so would you not send me back a url instead?

**Comment by edjames** [comment]
Ah right. 

If you're uploading a file from your local filesystem, then you would use the `path` argument, with the value of `path` being the absolute path to your local file.

We also support uploading files from remote locations (e.g. Dropbox). Typically this is used for very large files or when you have unreliable network connectivity. As long as your file is accessible via http, then you can use the `url` instead and we would handle that.

**Comment by onlymejosh** [comment]
Hmm. Maybe I’m not explaining myself clear enough.

I’m uploading directly to S3 using the vzaar-api-ruby gem to return the S3 signature for the form.
```
def new
  @signature = @vzaar_api.signature
  super
end
```

```
  <form id="s3uploadForm" action="https://<%= @signature.bucket %>.s3.amazonaws.com/" method="POST" enctype="multipart/form-data" class="video-form" data-guid="<%= @signature.guid %>">
    <input type="hidden" name="acl" id="acl" value="<%= @signature.acl %>">
    <input type="hidden" name="bucket" id="bucket" value="<%= @signature.bucket %>">
    <input type="hidden" name="policy" id="policy" value="<%= @signature.policy %>">
    <input type="hidden" name="AWSAccessKeyId" id="AWSAccessKeyId" value="<%= @signature.access_key_id %>">
    <input type="hidden" name="signature" id="signature" value="<%= @signature.signature %>">
    <input type="hidden" name="success_action_status" id="success_action_status" value="201">
    <input type="hidden" name="key" id="key" value="<%= @signature.key %>">
    
    <div class="field-unit field-unit--file">
      <div class="field-unit__label">
        <label for="file">Video File</label>
      </div>
      <div class="field-unit__field">
        <input type="file" name="file" id="file">
      </div>
    </div>
    <div class="field-unit field-unit--progress">
      <div class="field-unit__label">
        <label for="file">Progress</label>
      </div>
      <div class="field-unit__field">
        <div class="fileupload-progress"></div>
      </div>
    </div>
    <div class="form-actions">
      <a class="button upload-button">Upload</a>
    </div>
  </form>
```

I am using `jQueryFileUpload` to show a progress bar etc.

So with this code I can't sign with a path as I simply don't have one and won't be able to create one.

**Comment by edjames** [comment]
Doing it that way you would need to use a previous version of the gem. If you use the latest version you must now specify either `path` or `url` when generating a signature.

The reason for this is that we now support multipart uploads. When you request a signature, we check for the presence of 3 arguments: `path`, `filename` and `filesize`. If they are present then we decide whether we need to initiate a MultipartUpload on S3. If you use the gem on your backend, the the gem handles the `filename` and `filesize` values for you.

Specifying a `url` will bypass this functionality altogether.

If you want to use the latest version of the gem, and possibly take advantage of multipart uploads, then you need to dynamically generate the signature after your user has selected the file. You will then have both the path and file size values available via Javascript, which you can use to generate the signature.

Try taking a look at how this is implement in our demo app. The front end page for that app is [here](https://github.com/vzaar/chunked-browser-upload-reference-implementation/blob/master/client/index.html).
This is implemented using the [Plupload](http://www.plupload.com) Javascript library.

Let me know if you need any more help.
