### ISSUE TITLE
Doesn't connect using Rails 5

### ISSUE THREAD

**Issue by owen2345** [vzaar/vzaar-api-ruby#18]
I can not connect to API using this gem. It always returns 'Vzaar::Error: Protected Resource' for all methods.

**Comment by Joe-Crow** [comment]
Hi Owen, 

We're eager to help you, but the first thing to do is really confirm the vzaar credentials you're using to connect. 

As this issue is public, could you please reach out to support@vzaar.com referencing the issue and let us know your API credentials that way, so we can start to help?

**Comment by owen2345** [comment]
Hi Joe,
I sent an email to support@vzaar.com with my testing code.
Regards,
